### PR TITLE
Fixup for cacique installer

### PR DESCRIPTION
**Pull request by feniix**
Hello guys,

I did some modifications to the installer to have it run on a ubuntu LTS without almost any manual steps.

I tested it on ubuntu LTS 10.04.3 and it run flawlessly.

I hope it is added to your master branch.

### CODE REVIEW

**Comment by horaciob** [comment]
Hi fenix

Im Horacio, cacique's developer.
It's looks great!!,
Im going to check it and then Will commit those changes!!!

Thank you!!!! :)

If you want to make suggest or share cacique usage I would invite you to our
forum http://cacique.mercadolibre.com/forum/

**Comment by feniix** [comment]
The best way to test it is to install a vanilla ubuntu server lts 10.04.3 32bits
Then install git, 'apt-get install git-core' (I added apt-get install git-core to the script for the people that downloads the zip from github)
Then checkout the project from my github (read only = git://github.com/feniix/cacique.git) and then run the installer.

I tested it like that in a virtual machine and ran perfectly

I am starting the server using mongrel if that helps.

**Comment by horaciob** [comment]
Yes you right, if you have not installed then bundle install will get
problems

**Comment by feniix** [comment]
Any luck with this?

**Comment by feniix** [comment]
Hola Horacio, Pudieron testear el pull request?

**Comment by horaciob** [comment]
Sebastian,

Perdon No lo hemos comiteado, trate de ver si como hacer para aceptar un
commit desde github y no lo encontramos, vos sabes como se puede hacer para
aplicar directamente el parche?

**Comment by feniix** [comment]
y la mas facil (aparte de usar git fetch and git cherrypick que son un poco mas complicadas)  es editar el installer.sh a mano y modificar las lineas como muestra en https://github.com/mercadolibre/cacique/pull/3/files

**Comment by feniix** [comment]
Me rindo

**Pull request closed without merging**
